python GCN-test.py --run_num 1 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 2 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 3 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 4 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 5 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 6 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 7 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 8 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 9 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 10 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 11 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 12 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 13 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 14 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 15 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 16 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 17 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 18 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 19 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 20 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 21 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 22 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 23 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 24 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 25 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 26 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 27 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 28 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 29 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 30 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 31 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 32 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 33 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 34 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 35 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 36 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 37 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 38 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 39 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 40 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 41 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 42 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 43 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 44 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 45 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 46 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 47 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 48 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 49 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 50 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 51 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 52 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 53 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 54 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 55 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 56 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 57 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 58 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 59 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 60 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 61 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 62 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 63 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 64 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 65 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 66 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 67 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 68 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 69 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 70 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 71 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 72 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 73 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 74 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 75 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 76 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 77 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 78 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 79 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 80 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 81 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 82 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 83 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 84 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 85 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 86 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 87 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 88 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 89 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 90 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 91 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 92 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 93 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 94 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 95 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 96 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 97 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 98 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 99 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 100 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 101 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 102 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 103 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 104 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 105 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 106 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 107 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 108 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 109 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 110 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 111 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 112 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 113 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 114 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 115 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 116 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 117 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 118 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 119 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 120 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 121 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 122 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 123 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 124 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 125 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 126 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 127 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 128 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 129 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 130 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 131 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 132 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 133 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 134 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 135 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 136 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 137 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 138 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 139 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 140 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 141 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 142 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 143 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 144 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 145 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 146 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 147 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 148 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 149 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 150 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 151 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 152 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 153 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 154 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 155 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 156 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 157 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 158 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 159 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 160 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 161 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 162 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 163 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 164 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 165 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 166 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 167 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 168 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 169 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 170 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 171 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 172 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 173 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 174 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 175 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 176 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 177 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 178 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 179 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 180 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 181 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 182 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 183 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 184 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 185 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 186 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 187 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 188 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 189 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 190 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 191 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 192 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 193 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 194 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 195 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 196 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 197 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 198 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 199 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
python GCN-test.py --run_num 200 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:1
