##all-chameleon-0-1-0-0.5-0.5-0.1
#python GCN-test.py --run_num 1 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.1 --noheterophily 0.1
#python GCN-test.py --run_num 2 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.1 --noheterophily 0.2
#python GCN-test.py --run_num 3 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.1 --noheterophily 0.3
#python GCN-test.py --run_num 4 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.1 --noheterophily 0.4
#python GCN-test.py --run_num 5 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.1 --noheterophily 0.5
#python GCN-test.py --run_num 6 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.1 --noheterophily 0.6
#python GCN-test.py --run_num 7 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.1 --noheterophily 0.7
#python GCN-test.py --run_num 8 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.1 --noheterophily 0.8
#python GCN-test.py --run_num 9 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.1 --noheterophily 0.9
#python GCN-test.py --run_num 10 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.1 --noheterophily 1
#python GCN-test.py --run_num 11 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.1 --noheterophily 0.001
#
#python GCN-test.py --run_num 12 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.2 --noheterophily 0.1
#python GCN-test.py --run_num 13 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.2 --noheterophily 0.2
#python GCN-test.py --run_num 14 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.2 --noheterophily 0.3
#python GCN-test.py --run_num 15 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.2 --noheterophily 0.4
#python GCN-test.py --run_num 16 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.2 --noheterophily 0.5
#python GCN-test.py --run_num 17 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.2 --noheterophily 0.6
#python GCN-test.py --run_num 18 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.2 --noheterophily 0.7
#python GCN-test.py --run_num 19 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.2 --noheterophily 0.8
#python GCN-test.py --run_num 20 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.2 --noheterophily 0.9
#python GCN-test.py --run_num 21 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.2 --noheterophily 1
#python GCN-test.py --run_num 22 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.2 --noheterophily 0.001
#
#python GCN-test.py --run_num 23 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.3 --noheterophily 0.1
#python GCN-test.py --run_num 24 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.3 --noheterophily 0.2
#python GCN-test.py --run_num 25 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.3 --noheterophily 0.3
#python GCN-test.py --run_num 26 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.3 --noheterophily 0.4
#python GCN-test.py --run_num 27 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.3 --noheterophily 0.5
#python GCN-test.py --run_num 28 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.3 --noheterophily 0.6
#python GCN-test.py --run_num 29 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.3 --noheterophily 0.7
#python GCN-test.py --run_num 30 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.3 --noheterophily 0.8
#python GCN-test.py --run_num 9 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.3 --noheterophily 0.9
#python GCN-test.py --run_num 10 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.3 --noheterophily 1
#python GCN-test.py --run_num 10 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.3 --noheterophily 0.001
#
#python GCN-test.py --run_num 1 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.4 --noheterophily 0.1
#python GCN-test.py --run_num 2 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.4 --noheterophily 0.2
#python GCN-test.py --run_num 3 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.4 --noheterophily 0.3
#python GCN-test.py --run_num 4 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.4 --noheterophily 0.4
#python GCN-test.py --run_num 5 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.4 --noheterophily 0.5
#python GCN-test.py --run_num 6 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.4 --noheterophily 0.6
#python GCN-test.py --run_num 7 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.4 --noheterophily 0.7
#python GCN-test.py --run_num 8 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.4 --noheterophily 0.8
#python GCN-test.py --run_num 9 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.4 --noheterophily 0.9
#python GCN-test.py --run_num 10 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.4 --noheterophily 1
#python GCN-test.py --run_num 10 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.4 --noheterophily 0.001
#
#python GCN-test.py --run_num 1 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.5 --noheterophily 0.1
#python GCN-test.py --run_num 2 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.5 --noheterophily 0.2
#python GCN-test.py --run_num 3 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.5 --noheterophily 0.3
#python GCN-test.py --run_num 4 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.5 --noheterophily 0.4
#python GCN-test.py --run_num 5 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.5 --noheterophily 0.5
#python GCN-test.py --run_num 6 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.5 --noheterophily 0.6
#python GCN-test.py --run_num 7 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.5 --noheterophily 0.7
#python GCN-test.py --run_num 8 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.5 --noheterophily 0.8
#python GCN-test.py --run_num 9 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.5 --noheterophily 0.9
#python GCN-test.py --run_num 10 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.5 --noheterophily 1
#python GCN-test.py --run_num 10 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.5 --noheterophily 0.001
#
#python GCN-test.py --run_num 1 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.6 --noheterophily 0.1
#python GCN-test.py --run_num 60 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.6 --noheterophily 0.2
#python GCN-test.py --run_num 3 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.6 --noheterophily 0.3
#python GCN-test.py --run_num 4 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.6 --noheterophily 0.4
#python GCN-test.py --run_num 5 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.6 --noheterophily 0.5
#python GCN-test.py --run_num 6 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.6 --noheterophily 0.6
#python GCN-test.py --run_num 7 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.6 --noheterophily 0.7
#python GCN-test.py --run_num 8 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.6 --noheterophily 0.8
#python GCN-test.py --run_num 9 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.6 --noheterophily 0.9
#python GCN-test.py --run_num 10 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.6 --noheterophily 1
#python GCN-test.py --run_num 10 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.6 --noheterophily 0.001
#
#python GCN-test.py --run_num 1 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.7 --noheterophily 0.1
#python GCN-test.py --run_num 2 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.7 --noheterophily 0.2
#python GCN-test.py --run_num 3 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.7 --noheterophily 0.3
#python GCN-test.py --run_num 4 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.7 --noheterophily 0.4
#python GCN-test.py --run_num 5 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.7 --noheterophily 0.5
#python GCN-test.py --run_num 6 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.7 --noheterophily 0.6
#python GCN-test.py --run_num 7 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.7 --noheterophily 0.7
#python GCN-test.py --run_num 8 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.7 --noheterophily 0.8
#python GCN-test.py --run_num 9 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.7 --noheterophily 0.9
#python GCN-test.py --run_num 10 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.7 --noheterophily 1
#python GCN-test.py --run_num 10 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.7 --noheterophily 0.001
#
#python GCN-test.py --run_num 1 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.8 --noheterophily 0.1
#python GCN-test.py --run_num 2 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.8 --noheterophily 0.2
#python GCN-test.py --run_num 3 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.8 --noheterophily 0.3
#python GCN-test.py --run_num 4 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.8 --noheterophily 0.4
#python GCN-test.py --run_num 5 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.8 --noheterophily 0.5
#python GCN-test.py --run_num 6 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.8 --noheterophily 0.6
#python GCN-test.py --run_num 7 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.8 --noheterophily 0.7
#python GCN-test.py --run_num 8 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.8 --noheterophily 0.8
#python GCN-test.py --run_num 9 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.8 --noheterophily 0.9
#python GCN-test.py --run_num 10 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.8 --noheterophily 1
#python GCN-test.py --run_num 10 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.8 --noheterophily 0.001
#
#python GCN-test.py --run_num 1 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.9 --noheterophily 0.1
#python GCN-test.py --run_num 2 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.9 --noheterophily 0.2
#python GCN-test.py --run_num 3 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.9 --noheterophily 0.3
#python GCN-test.py --run_num 4 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.9 --noheterophily 0.4
#python GCN-test.py --run_num 5 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.9 --noheterophily 0.5
#python GCN-test.py --run_num 6 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.9 --noheterophily 0.6
#python GCN-test.py --run_num 7 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.9 --noheterophily 0.7
#python GCN-test.py --run_num 8 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.9 --noheterophily 0.8
#python GCN-test.py --run_num 9 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.9 --noheterophily 0.9
#python GCN-test.py --run_num 10 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.9 --noheterophily 1
#python GCN-test.py --run_num 10 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.9 --noheterophily 0.001
#
#python GCN-test.py --run_num 1 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 1.0 --noheterophily 0.1
#python GCN-test.py --run_num 2 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 1.0 --noheterophily 0.2
#python GCN-test.py --run_num 3 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 1.0 --noheterophily 0.3
#python GCN-test.py --run_num 110 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 1.0 --noheterophily 0.4
#python GCN-test.py --run_num 5 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 1.0 --noheterophily 0.5
#python GCN-test.py --run_num 6 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 1.0 --noheterophily 0.6
#python GCN-test.py --run_num 7 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 1.0 --noheterophily 0.7
#python GCN-test.py --run_num 8 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 1.0 --noheterophily 0.8
#python GCN-test.py --run_num 9 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 1.0 --noheterophily 0.9
#python GCN-test.py --run_num 10 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 1.0 --noheterophily 1
#python GCN-test.py --run_num 10 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 1.0 --noheterophily 0.001

python GCN-test.py --run_num 1 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.001 --noheterophily 0.1
python GCN-test.py --run_num 2 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.001 --noheterophily 0.2
python GCN-test.py --run_num 3 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.001 --noheterophily 0.3
python GCN-test.py --run_num 4 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.001 --noheterophily 0.4
python GCN-test.py --run_num 5 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.001 --noheterophily 0.5
python GCN-test.py --run_num 6 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.001 --noheterophily 0.6
python GCN-test.py --run_num 7 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.001 --noheterophily 0.7
python GCN-test.py --run_num 8 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.001 --noheterophily 0.8
python GCN-test.py --run_num 9 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.001 --noheterophily 0.9
python GCN-test.py --run_num 10 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.001 --noheterophily 1
python GCN-test.py --run_num 10 --dataset chameleon --conv True    --otherEmbeding True  --typeEmbeding HGT  --diffusion True  --device cuda:0 --heterophily 0.001 --noheterophily 0.001
